// ============================================================
// DONNÉES — Destinations depuis le vault Obsidian
// ============================================================

const DESTINATIONS = [
  // ── VOYAGE CONFIRMÉ ──────────────────────────────────────
  {
    id: "heraklion",
    nom: "Crète — Héraklion",
    pays: "Grèce",
    emoji: "🏖️",
    statut: "confirme",
    budget_min: 1950, budget_max: 1950,
    dates: "6–11 juillet 2026",
    date_depart: "2026-07-06", date_retour: "2026-07-11",
    coords: [35.3387, 25.1442],
    vol: "CDG 07:50 → HER | HER 13:20 → CDG (TUI)",
    vol_prix: "Inclus TUI",
    compagnie: "TUI",
    iata: "HER",
    logement: "TUI Suneo Chrissi Amoudia ★★★★ — All-inclusive",
    type: ["plage", "culture", "randonnee"],
    budget_restant: 420,
    description: "5 nuits en Crète dans un hôtel all-inclusive TUI. Knossos, Gorges de Samaria, Spinalonga, excursion île de Dia.",
    pois: [
      { nom: "Palais de Knossos", type: "culture", coords: [35.2985, 25.1631], prix: "16€/pers", lien: "https://e-ticketing.culture.gov.gr", site: "https://e-ticketing.culture.gov.gr", horaires: "Été : 08h00–20h00 (dernière entrée 19h30)" },
      { nom: "Gorges de Samaria", type: "randonnee", coords: [35.2928, 23.9714], prix: "35-50€/pers (excursion)", lien: "https://samaria-tickets.necca.gov.gr" },
      { nom: "Île de Spinalonga", type: "culture", coords: [35.2979, 25.7309], prix: "8€/pers + bateau ~15€", lien: "" },
      { nom: "Hersonissos", type: "detente", coords: [35.4073, 25.4044], prix: "Gratuit", lien: "" },
      { nom: "Ruines de Malia", type: "culture", coords: [35.2978, 25.5175], prix: "6€/pers", lien: "" },
      { nom: "Koutouloufari", type: "restaurant", coords: [35.4021, 25.3797], prix: "~25-30€/pers", lien: "" },
    ],
    restaurants: [
      { nom: "Taverne à Koutouloufari (village)", note: "★★★★★", type: "Cuisine crétoise traditionnelle", prix: "~25€/pers", horaires: "Généralement 18h00–23h00", coords: [35.4021, 25.3797], site: "https://www.google.com/maps/search/restaurant+Koutouloufari" },
      { nom: "Restaurants du port d'Elounda", note: "★★★★", type: "Fruits de mer, poulpe grillé", prix: "~25€/pers", coords: [35.2603, 25.7236], site: "https://www.google.com/maps/search/taverne+Elounda+port" },
    ],
    gastronomie: ["Dakos (salade crétoise)", "Poulpe grillé", "Fromage graviera", "Miel de thym", "Raki"],
    urgences: [{ service: "Hôpital Hersonissos", tel: "+30 28970 22222" }, { service: "Consulat France", tel: "+30 210 339 1000" }],
    liens: [
      { label: "Knossos (billetterie)", url: "https://e-ticketing.culture.gov.gr" },
      { label: "Gorges de Samaria", url: "https://samaria-tickets.necca.gov.gr/checkout" },
      { label: "Ferry ANENDYK", url: "https://anendyk.gr" },
      { label: "Fantasia Yachting", url: "https://www.fantasiayachting.com" },
      { label: "Météo marine Crète", url: "https://www.poseidon.hcmr.gr" },
      { label: "CEAM (ameli.fr)", url: "https://www.ameli.fr/assure/droits-demarches/europe-international" },
    ],
    valise_type: "plage_randonnee",
    meteo: { temp: "32-36°C", mer: "26-27°C", nuit: "22-24°C" },
    routard: {
      url: "https://www.routard.com/fr/guide/europe/grece/crete",
      resume: "La Crète mêle sites minoens, gorges sauvages et plages turquoise. En séjour court, mieux vaut se concentrer soit sur l'Est soit sur l'Ouest.",
      incontournables: [
        "La Canée (Hania), joyau vénitien de l'ouest de l'île",
        "Site minoen de Knossos (5 km d'Héraklion) + Musée archéologique",
        "Gorges de Samaria, les plus longues d'Europe",
        "Lagon rose et turquoise d'Élafonissi",
        "Xerokampos à l'extrême Est : plages calmes de la Crète d'autrefois",
      ],
      conseils: [
        "Décalage horaire +1h avec la France",
        "≈3h30 de vol direct depuis Paris pour Héraklion",
        "Bus partout mais lent ; la voiture donne une vraie autonomie",
        "Peu de temps ? Choisir l'Est OU l'Ouest ; 10 jours pour une bonne partie",
      ],
    },
  },

  // ── PROJETS ACTIFS 2026 ───────────────────────────────────
  {
    id: "porto",
    nom: "Porto",
    pays: "Portugal",
    emoji: "🍷",
    statut: "planification",
    budget_min: 746, budget_max: 1130,
    dates: "6–10 juillet 2026",
    date_depart: "2026-07-06", date_retour: "2026-07-10",
    coords: [41.1579, -8.6291],
    vol: "Transavia NTE → OPO direct 1h50",
    vol_prix: "231€ AR pour 2",
    compagnie: "Transavia",
    iata: "OPO",
    logement: "Appartement Ribeira / Bolhão — 55-89€/nuit",
    type: ["ville", "culture", "gastronomie"],
    description: "Porto en 4 nuits : caves de Vila Nova de Gaia, Livraria Lello, Pont Dom Luís, excursion Vallée du Douro.",
    pois: [
      { nom: "Caves de Vila Nova de Gaia", type: "culture", coords: [41.1385, -8.6139], prix: "~15€/pers", lien: "https://www.cvrvv.pt" },
      { nom: "Livraria Lello", type: "culture", coords: [41.1462, -8.6147], prix: "~5€ (déduits d'un achat)", lien: "https://www.livrarialello.pt", site: "https://www.livrarialello.pt", horaires: "Tous les jours ~09h00–19h00 (billet horodaté conseillé)" },
      { nom: "Pont Dom Luís", type: "detente", coords: [41.1400, -8.6094], prix: "Gratuit", lien: "" },
      { nom: "Vallée du Douro", type: "excursion", coords: [41.1828, -7.5431], prix: "~11€/pers (train)", lien: "" },
      { nom: "Plage de Matosinhos", type: "plage", coords: [41.1828, -8.6981], prix: "Gratuit", lien: "" },
      { nom: "Igreja São Francisco", type: "culture", coords: [41.1414, -8.6157], prix: "~6€/pers", lien: "" },
    ],
    restaurants: [
      { nom: "Restaurants Matosinhos", note: "★★★★★", type: "Poissons grillés, fruits de mer", prix: "~20€/pers" },
    ],
    gastronomie: ["Francesinha", "Bacalhau", "Pastel de nata", "Vinho verde", "Porto tónico"],
    liens: [
      { label: "Transavia NTE→OPO", url: "https://www.transavia.com" },
      { label: "Livraria Lello", url: "https://www.livrarialello.pt" },
      { label: "Visit Porto", url: "https://www.visitporto.travel" },
    ],
    valise_type: "ville",
    meteo: { temp: "25-30°C", mer: "19°C (Atlantique)", nuit: "17-20°C" },
    routard: {
      url: "https://www.routard.com/guide_a_voir/porto.htm",
      resume: "Ville de pentes et d'azulejos sur les rives du Douro, célèbre pour ses caves de vin de Porto.",
      incontournables: [
        "Traverser le pont Dom-Luís (le conseil n°1 du Routard)",
        "Panorama au coucher du soleil depuis Gaia (rive gauche)",
        "Marché de Bolhão magnifiquement rénové",
        "Librairie Lello (ticket-voucher en ligne avec créneau impératif)",
        "La tournée des caves à vin de Porto à Vila Nova de Gaia",
      ],
      conseils: [
        "Acheter la carte Andante dès l'aéroport (métro, bus, trains urbains)",
        "Pentes rudes : Uber/Bolt très abordables pour remonter au centre",
        "Meilleure période : printemps (fin avril–fin juin) et automne (sept–début oct)",
      ],
    },
  },
  {
    id: "florence",
    nom: "Florence",
    pays: "Italie",
    emoji: "🌸",
    statut: "planification",
    budget_min: 1023, budget_max: 1272,
    dates: "6–10 juillet 2026",
    date_depart: "2026-07-06", date_retour: "2026-07-10",
    coords: [43.7696, 11.2558],
    vol: "Volotea NTE → PSA direct + train Pise→Florence",
    vol_prix: "198€ AR pour 2 + ~40€ train",
    compagnie: "Volotea",
    iata: "PSA",
    logement: "Appartement centre historique — 90-120€/nuit",
    type: ["ville", "culture", "art"],
    description: "Florence en 4 nuits : Uffizi, Duomo, David de Michel-Ange, Ponte Vecchio, collines toscanes.",
    pois: [
      { nom: "Galerie des Offices (Uffizi)", type: "culture", coords: [43.7677, 11.2553], prix: "~20€/pers", lien: "https://www.uffizi.it", site: "https://www.uffizi.it/en/tickets", horaires: "Mar–Dim 08h15–18h30 · fermé lundi" },
      { nom: "Duomo (Santa Maria del Fiore)", type: "culture", coords: [43.7731, 11.2560], prix: "~18€ (coupole)", lien: "" },
      { nom: "David de Michel-Ange (Accademia)", type: "culture", coords: [43.7766, 11.2586], prix: "~12€/pers", lien: "" },
      { nom: "Ponte Vecchio", type: "detente", coords: [43.7681, 11.2531], prix: "Gratuit", lien: "" },
      { nom: "Piazzale Michelangelo", type: "detente", coords: [43.7629, 11.2651], prix: "Gratuit", lien: "" },
      { nom: "Jardin de Boboli", type: "detente", coords: [43.7640, 11.2489], prix: "~10€/pers", lien: "" },
    ],
    gastronomie: ["Bistecca alla Fiorentina", "Lampredotto (tripe)", "Ribollita", "Gelato artigianale", "Chianti Classico"],
    liens: [
      { label: "Uffizi (billetterie)", url: "https://www.uffizi.it/en/tickets" },
      { label: "Visit Florence", url: "https://www.visitflorence.com" },
    ],
    valise_type: "ville",
    meteo: { temp: "30-35°C", nuit: "20-22°C" },
    routard: {
      url: "https://www.routard.com/guide_a_voir/florence.htm",
      resume: "Berceau de la Renaissance : Duomo, Offices et David. Le Routard conseille 3 à 4 jours.",
      incontournables: [
        "Monter au sommet de la coupole du Duomo",
        "Galerie des Offices (Botticelli, Vinci, Michel-Ange, Raphaël)",
        "Le David à la Galerie de l'Accademia",
        "Ponte Vecchio, Palazzo Vecchio & Piazza della Signoria",
        "Musée du Bargello (sculptures de Donatello, premiers marbres de Michel-Ange)",
        "Le quartier de l'Oltrarno (Santo Spirito, San Frediano)",
      ],
      conseils: [
        "Réservation en ligne Offices + Accademia (David) indispensable, via les sites officiels dès l'ouverture des créneaux",
        "Manger bistecca alla fiorentina ou panini au lampredotto hors des menus touristiques (Oltrarno)",
        "Mercato Centrale & marché couvert San Lorenzo le matin",
        "3-4 jours conseillés ; printemps/automne idéals (moins de foule qu'en été)",
      ],
    },
  },
  {
    id: "perigord",
    nom: "Périgord Noir",
    pays: "France",
    emoji: "🌿",
    statut: "planification",
    budget_min: 656, budget_max: 1118,
    dates: "6–10 juillet 2026",
    date_depart: "2026-07-06", date_retour: "2026-07-10",
    coords: [44.9667, 1.0833],
    vol: "Voiture depuis Nantes (~200€ aller-retour)",
    vol_prix: "~200€ carburant + péages",
    compagnie: "Voiture",
    type: ["nature", "culture", "gastronomie"],
    description: "Périgord Noir en 4 nuits : Sarlat, grottes de Lascaux, vallée de la Dordogne, bastides médiévales.",
    pois: [
      { nom: "Sarlat-la-Canéda", type: "culture", coords: [44.8892, 1.2172], prix: "Gratuit", lien: "" },
      { nom: "Lascaux IV", type: "culture", coords: [45.0539, 1.1706], prix: "~20€/pers", lien: "https://www.lascaux.fr" },
      { nom: "Château de Castelnaud", type: "culture", coords: [44.8186, 1.1561], prix: "~12€/pers", lien: "" },
      { nom: "Roque-Gageac", type: "detente", coords: [44.8244, 1.1867], prix: "Gratuit", lien: "" },
      { nom: "Gouffre de Padirac", type: "culture", coords: [44.8544, 1.7500], prix: "~18€/pers", lien: "" },
    ],
    gastronomie: ["Foie gras", "Confit de canard", "Truffe noire", "Noix du Périgord", "Vin de Bergerac"],
    liens: [
      { label: "Lascaux IV", url: "https://www.lascaux.fr" },
    ],
    valise_type: "nature",
    meteo: { temp: "28-34°C", nuit: "16-20°C" },
    routard: {
      url: "https://www.routard.com/fr/guide/france/aquitaine-bordelais-landes/perigord-dordogne/sarlat",
      resume: "Sarlat, cité médiévale en pierre blonde, châteaux, grottes ornées et vallée de la Dordogne.",
      incontournables: [
        "Sarlat-la-Canéda, cité médiévale très préservée (forte densité de monuments classés)",
        "Jardins de Marqueyssac à Vézac (buis taillés, panorama sur la Dordogne)",
        "Château de Castelnaud + musée de la Guerre au Moyen Âge",
        "Lascaux IV à Montignac (réplique bluffante de la grotte ornée)",
        "Canoë-kayak sur la Dordogne et la Vézère (falaises et châteaux depuis l'eau)",
      ],
      conseils: [
        "Été = foule ; printemps et automne plus sereins et colorés",
        "1 journée pour le centre de Sarlat, plusieurs jours pour profiter des environs",
      ],
    },
  },
  {
    id: "madrid",
    nom: "Madrid",
    pays: "Espagne",
    emoji: "🇪🇸",
    statut: "planification",
    budget_min: 900, budget_max: 1400,
    dates: "Projet 2026",
    coords: [40.4168, -3.7038],
    vol: "Vol depuis NTE — ~180-280€ AR",
    vol_prix: "180-280€ AR pour 2",
    compagnie: "Vueling / Iberia",
    iata: "MAD",
    logement: "Appartement centre — 70-100€/nuit",
    type: ["ville", "culture", "gastronomie"],
    description: "Madrid : Prado, Reina Sofía, Retiro, tapas et marché San Miguel.",
    pois: [
      { nom: "Musée du Prado", type: "culture", coords: [40.4138, -3.6922], prix: "~15€/pers", lien: "https://www.museodelprado.es", site: "https://www.museodelprado.es/en/visit-the-museum", horaires: "Lun–Sam 10h00–20h00 · Dim 10h00–19h00 · gratuit 18h–20h" },
      { nom: "Musée Reina Sofía", type: "culture", coords: [40.4082, -3.6944], prix: "~12€/pers", lien: "" },
      { nom: "Parc du Retiro", type: "detente", coords: [40.4152, -3.6845], prix: "Gratuit", lien: "" },
      { nom: "Marché San Miguel", type: "gastronomie", coords: [40.4152, -3.7089], prix: "Gratuit (tapas ~2-3€/pièce)", lien: "" },
    ],
    gastronomie: ["Jamón ibérico", "Tortilla española", "Churros con chocolate", "Cocido madrileño", "Sangria"],
    valise_type: "ville",
    meteo: { temp: "30-38°C", nuit: "18-22°C" },
    routard: {
      url: "https://www.routard.com/fr/guide/europe/espagne/madrid",
      resume: "Capitale festive du « triangle de l'art », des tapas et des quartiers branchés de la Movida.",
      incontournables: [
        "Musée du Prado (classicisme)",
        "Musée Thyssen-Bornemisza (panorama de la peinture)",
        "Centro de Arte Reina Sofía (art contemporain)",
        "Tapas de bar en bar (au moins une soirée complète)",
        "Marché de San Miguel + Puerta del Sol (kilomètre zéro)",
        "Quartiers de la Movida : Chueca, La Latina, Lavapiés",
      ],
      conseils: [
        "Acheter la carte Multi dès l'aéroport pour les transports",
        "Meilleures saisons : printemps ou automne, températures agréables, sans la foule",
      ],
    },
  },
  {
    id: "amsterdam",
    nom: "Amsterdam",
    pays: "Pays-Bas",
    emoji: "🚲",
    statut: "planification",
    budget_min: 1000, budget_max: 1600,
    dates: "Projet 2026",
    coords: [52.3676, 4.9041],
    vol: "Vol depuis NTE — ~200-350€ AR",
    vol_prix: "200-350€ AR pour 2",
    compagnie: "easyJet / Transavia",
    iata: "AMS",
    logement: "Appartement centre — 100-150€/nuit",
    type: ["ville", "culture", "velo"],
    description: "Amsterdam : Rijksmuseum, Anne Frank, canaux, Jordaan, vélo.",
    pois: [
      { nom: "Rijksmuseum", type: "culture", coords: [52.3600, 4.8852], prix: "~22€/pers", lien: "https://www.rijksmuseum.nl", site: "https://www.rijksmuseum.nl/fr/visiter", horaires: "Tous les jours 09h00–17h00" },
      { nom: "Maison d'Anne Frank", type: "culture", coords: [52.3752, 4.8840], prix: "~16€/pers", lien: "https://www.annefrank.org", site: "https://www.annefrank.org/fr/musee/billets/", horaires: "Billets en ligne uniquement, créneau horodaté obligatoire" },
      { nom: "Van Gogh Museum", type: "culture", coords: [52.3584, 4.8811], prix: "~22€/pers", lien: "" },
      { nom: "Quartier Jordaan", type: "detente", coords: [52.3752, 4.8787], prix: "Gratuit", lien: "" },
    ],
    gastronomie: ["Stroopwafel", "Bitterballen", "Haring (hareng cru)", "Poffertjes", "Jenever (genièvre)"],
    valise_type: "ville",
    meteo: { temp: "20-25°C", nuit: "14-18°C" },
    routard: {
      url: "https://www.routard.com/fr/guide/europe/pays-bas/amsterdam",
      resume: "Ville des canaux du Siècle d'or, à parcourir à pied ou à vélo.",
      incontournables: [
        "Maison d'Anne Frank",
        "Rijksmuseum + Musée Van Gogh",
        "Ceinture de canaux (Grachtengordel : Singel, Herengracht, Keizersgracht, Prinsengracht)",
        "Le Béguinage (Het Begijnhof)",
        "Cinéma Tuschinski et le Quartier Rouge",
      ],
      conseils: [
        "Ville qui se parcourt à pied ou à vélo (le vélo est roi)",
        "Goûter la rijsttafel indonésienne et les « cafés bruns » (bière, genièvre)",
        "Printemps/automne ; avril-mai = moins de pluie + tulipes (15 avril–15 mai)",
      ],
    },
  },
  {
    id: "minorque",
    nom: "Minorque",
    pays: "Espagne",
    emoji: "🏝️",
    statut: "planification",
    budget_min: 900, budget_max: 1400,
    dates: "Projet 2026",
    coords: [39.9495, 4.1090],
    vol: "Vol depuis NTE — ~200-300€ AR",
    vol_prix: "200-300€ AR pour 2",
    compagnie: "Vueling / Iberia",
    iata: "MAH",
    logement: "Appartement ou villa — 90-140€/nuit",
    type: ["plage", "nature", "detente"],
    description: "Minorque : réserve de biosphère UNESCO, criques sauvages, Cala Macarella, citadelle de Ciutadella.",
    pois: [
      { nom: "Cala Macarella", type: "plage", coords: [39.8897, 3.8267], prix: "Gratuit", lien: "" },
      { nom: "Ciutadella", type: "culture", coords: [40.0028, 3.8285], prix: "Gratuit", lien: "" },
      { nom: "Fortalesa de la Mola", type: "culture", coords: [39.9066, 4.2810], prix: "~5€/pers", lien: "" },
    ],
    gastronomie: ["Caldereta de Llagosta (homard)", "Queso de Mahón", "Gin de Mahón", "Ensaimada", "Sobrasada"],
    valise_type: "plage",
    meteo: { temp: "28-32°C", mer: "24-26°C", nuit: "20-22°C" },
    routard: {
      url: "https://www.routard.com/fr/guide/europe/espagne/baleares/minorque",
      resume: "Réserve de biosphère Unesco, la plus discrète des Baléares, aux criques translucides.",
      incontournables: [
        "Ciutadella et son port (départ des excursions en bateau)",
        "Criques du sud : Cala en Turqueta, Son Saura, Cala Macarella",
        "Parc natural de S'Albufera d'es Grau",
        "Phares de Cavalleria et de Favàritx",
        "Fornells et Cala Mitjana",
      ],
      conseils: [
        "Criques Macarella/Macarelleta : accès voiture interdit l'été → réserver la navette (bus 69) en ligne plusieurs jours avant depuis Ciutadella",
        "Marcher des tronçons du GR 223 (Camí de Cavalls) pour ressentir l'âme de l'île",
      ],
    },
  },

  // ── PROJETS FUTURS EUROPE ─────────────────────────────────
  {
    id: "athenes",
    nom: "Athènes",
    pays: "Grèce",
    emoji: "🏛️",
    statut: "projet",
    budget_min: 1200, budget_max: 1600,
    coords: [37.9838, 23.7275],
    vol: "Correspondance via CDG — ~530-820€ AR",
    vol_prix: "530-820€ AR pour 2",
    compagnie: "Air France / KLM",
    iata: "ATH",
    logement: "Appartement Koukaki / Monastiraki — 52-81€/nuit",
    type: ["ville", "culture", "histoire"],
    description: "Athènes : Acropole, Parthénon, Musée Archéologique, Agora antique, Cap Sounion.",
    pois: [
      { nom: "Acropole & Parthénon", type: "culture", coords: [37.9715, 23.7267], prix: "~20€/pers", lien: "https://etickets.tap.gr", site: "https://etickets.tap.gr", horaires: "Été : 08h00–20h00 (créneau horaire à réserver l'été)" },
      { nom: "Musée de l'Acropole", type: "culture", coords: [37.9681, 23.7286], prix: "~10€/pers", lien: "" },
      { nom: "Agora antique", type: "culture", coords: [37.9752, 23.7216], prix: "~10€/pers", lien: "" },
      { nom: "Cap Sounion", type: "excursion", coords: [37.6503, 24.0268], prix: "~7€ bus + ~8€ entrée", lien: "" },
      { nom: "Île d'Égine (ferry)", type: "excursion", coords: [37.7458, 23.4249], prix: "~15-20€ ferry AR", lien: "" },
    ],
    gastronomie: ["Souvlaki / Gyros", "Tzatziki, taramosalata", "Loukoumades", "Café frappé", "Vin retsina"],
    valise_type: "ville",
    meteo: { temp: "30-36°C", nuit: "22-25°C" },
  },
  {
    id: "berlin",
    nom: "Berlin",
    pays: "Allemagne",
    emoji: "🐻",
    statut: "projet",
    budget_min: 950, budget_max: 1500,
    coords: [52.5200, 13.4050],
    vol: "Correspondance via CDG — ~220-380€ AR",
    vol_prix: "220-380€ AR pour 2",
    compagnie: "easyJet / Lufthansa",
    iata: "BER",
    logement: "Appartement Friedrichshain / Kreuzberg — 65-100€/nuit",
    type: ["ville", "culture", "histoire", "streetart"],
    description: "Berlin : East Side Gallery, Museumsinsel, Checkpoint Charlie, Reichstag, Mauerpark.",
    pois: [
      { nom: "East Side Gallery", type: "culture", coords: [52.5055, 13.4398], prix: "Gratuit", lien: "" },
      { nom: "Museumsinsel (UNESCO)", type: "culture", coords: [52.5169, 13.4012], prix: "~18€/pers", lien: "https://www.smb.museum" },
      { nom: "Mémorial de l'Holocauste", type: "culture", coords: [52.5139, 13.3784], prix: "Gratuit", lien: "" },
      { nom: "Dôme du Reichstag", type: "culture", coords: [52.5186, 13.3762], prix: "Gratuit (résa obligatoire)", lien: "https://www.bundestag.de" },
      { nom: "Schloss Charlottenburg", type: "culture", coords: [52.5203, 13.2956], prix: "~12€/pers", lien: "" },
    ],
    gastronomie: ["Currywurst", "Döner kebap berlinois", "Pretzel (Brezel)", "Berliner Weiße", "KaDeWe (6ème étage)"],
    valise_type: "ville",
    meteo: { temp: "20-28°C", nuit: "13-17°C" },
  },
  {
    id: "munich",
    nom: "Munich",
    pays: "Allemagne",
    emoji: "🍺",
    statut: "projet",
    budget_min: 1000, budget_max: 1600,
    coords: [48.1351, 11.5820],
    vol: "Correspondance — ~250-400€ AR",
    vol_prix: "250-400€ AR pour 2",
    compagnie: "Lufthansa / easyJet",
    iata: "MUC",
    logement: "Appartement centre ou Schwabing — 80-120€/nuit",
    type: ["ville", "culture", "biere", "nature"],
    description: "Munich : Englischer Garten, Marienplatz, Hofbräuhaus, Nymphenburg, Allianz Arena.",
    pois: [
      { nom: "Englischer Garten", type: "nature", coords: [48.1641, 11.6054], prix: "Gratuit", lien: "" },
      { nom: "Marienplatz & Carillon", type: "culture", coords: [48.1374, 11.5755], prix: "Gratuit", lien: "" },
      { nom: "Hofbräuhaus", type: "gastronomie", coords: [48.1376, 11.5800], prix: "~15-20€/pers", lien: "" },
      { nom: "Schloss Nymphenburg", type: "culture", coords: [48.1581, 11.5033], prix: "~8€/pers", lien: "" },
      { nom: "Musée Deutsches Museum", type: "culture", coords: [48.1300, 11.5833], prix: "~15€/pers", lien: "" },
    ],
    gastronomie: ["Weißwurst (saucisse blanche)", "Brez'n (pretzel)", "Schnitzel", "Maß (1L de bière)", "Obatzda (fromage)"],
    valise_type: "ville",
    meteo: { temp: "22-28°C", nuit: "13-17°C" },
  },
  {
    id: "prague",
    nom: "Prague",
    pays: "République Tchèque",
    emoji: "🏰",
    statut: "projet",
    budget_min: 780, budget_max: 1200,
    coords: [50.0755, 14.4378],
    vol: "Direct ou correspondance — ~150-250€ AR",
    vol_prix: "150-250€ AR pour 2",
    compagnie: "Ryanair / easyJet",
    iata: "PRG",
    logement: "Appartement Vinohrady / Žižkov — 50-80€/nuit",
    type: ["ville", "culture", "histoire"],
    description: "Prague : Château de Prague, Pont Charles, Vieille ville, synagogues, Josefov.",
    pois: [
      { nom: "Château de Prague", type: "culture", coords: [50.0902, 14.4002], prix: "~12€/pers", lien: "" },
      { nom: "Pont Charles", type: "culture", coords: [50.0865, 14.4114], prix: "Gratuit", lien: "" },
      { nom: "Vieille Ville (Staré Město)", type: "culture", coords: [50.0872, 14.4216], prix: "Gratuit", lien: "" },
      { nom: "Quartier Juif (Josefov)", type: "culture", coords: [50.0899, 14.4170], prix: "~15€/pers", lien: "" },
    ],
    gastronomie: ["Svíčková (bœuf à la crème)", "Trdelník", "Knedlíky (quenelles)", "Pilsner Urquell", "Svařák (vin chaud)"],
    valise_type: "ville",
    meteo: { temp: "22-28°C", nuit: "13-17°C" },
  },
  {
    id: "tirana",
    nom: "Tirana + Berat",
    pays: "Albanie",
    emoji: "🦅",
    statut: "projet",
    budget_min: 800, budget_max: 1300,
    coords: [41.3275, 19.8187],
    vol: "Correspondance — ~200-350€ AR",
    vol_prix: "200-350€ AR pour 2",
    compagnie: "Wizzair / Turkish Airlines",
    iata: "TIA",
    logement: "Appartement centre — 30-50€/nuit (très abordable)",
    type: ["ville", "culture", "histoire"],
    description: "Tirana + Berat (UNESCO) : destination émergente, très abordable, architecture communiste, vieille ville de Berat.",
    pois: [
      { nom: "Blloku (quartier branché)", type: "detente", coords: [41.3171, 19.8172], prix: "Gratuit", lien: "" },
      { nom: "Piramide de Tirana", type: "culture", coords: [41.3230, 19.8200], prix: "Gratuit", lien: "" },
      { nom: "Berat — Vieille ville (UNESCO)", type: "culture", coords: [40.7058, 19.9444], prix: "Gratuit", lien: "" },
    ],
    gastronomie: ["Byrek (feuilleté)", "Tavë kosi (agneau au yaourt)", "Fergese (tomates, poivrons, fromage)", "Raki albanais"],
    valise_type: "ville",
    meteo: { temp: "28-35°C", nuit: "18-22°C" },
  },
  {
    id: "stockholm",
    nom: "Stockholm",
    pays: "Suède",
    emoji: "👑",
    statut: "projet",
    budget_min: 1200, budget_max: 2000,
    coords: [59.3293, 18.0686],
    vol: "Direct ou correspondance — ~250-400€ AR",
    vol_prix: "250-400€ AR pour 2",
    compagnie: "SAS / easyJet",
    iata: "ARN",
    logement: "Appartement Södermalm / Östermalm — 100-150€/nuit",
    type: ["ville", "culture", "nature"],
    description: "Stockholm : Gamla Stan, Vasa Museum, archipel, Djurgården, Skansen.",
    pois: [
      { nom: "Gamla Stan (vieille ville)", type: "culture", coords: [59.3250, 18.0700], prix: "Gratuit", lien: "" },
      { nom: "Vasa Museum", type: "culture", coords: [59.3280, 18.0914], prix: "~19€/pers", lien: "https://www.vasamuseet.se" },
      { nom: "Djurgården", type: "nature", coords: [59.3350, 18.1050], prix: "Gratuit", lien: "" },
      { nom: "Archipel de Stockholm", type: "excursion", coords: [59.4000, 18.3000], prix: "~15-25€ ferry", lien: "" },
    ],
    gastronomie: ["Köttbullar (boulettes)", "Smörgåsbord", "Kanelbulle (brioche cannelle)", "Gravlax", "Aquavit"],
    valise_type: "ville",
    meteo: { temp: "18-24°C", nuit: "12-16°C" },
  },
  {
    id: "oslo",
    nom: "Oslo",
    pays: "Norvège",
    emoji: "🌅",
    statut: "projet",
    budget_min: 1400, budget_max: 2200,
    coords: [59.9139, 10.7522],
    vol: "Direct ou correspondance — ~300-500€ AR",
    vol_prix: "300-500€ AR pour 2",
    compagnie: "Norwegian / SAS",
    iata: "OSL",
    logement: "Appartement Grünerløkka — 120-170€/nuit",
    type: ["ville", "culture", "nature"],
    description: "Oslo : Vigelandsparken, Munch, Opéra, fjord d'Oslo, Holmenkollen.",
    pois: [
      { nom: "Vigelandsparken", type: "culture", coords: [59.9272, 10.7000], prix: "Gratuit", lien: "" },
      { nom: "Musée Munch", type: "culture", coords: [59.9059, 10.7533], prix: "~19€/pers", lien: "" },
      { nom: "Opéra d'Oslo", type: "culture", coords: [59.9075, 10.7533], prix: "Gratuit (toit)", lien: "" },
      { nom: "Fjord d'Oslo (croisière)", type: "excursion", coords: [59.8900, 10.7500], prix: "~15-20€", lien: "" },
    ],
    gastronomie: ["Laks (saumon)", "Fårikål (mouton-chou)", "Brunost (fromage brun)", "Gravlax", "Aquavit"],
    valise_type: "ville",
    meteo: { temp: "18-24°C", nuit: "12-15°C" },
  },
  {
    id: "bergen",
    nom: "Bergen & Fjords",
    pays: "Norvège",
    emoji: "🌊",
    statut: "projet",
    budget_min: 1500, budget_max: 2500,
    coords: [60.3913, 5.3221],
    vol: "Correspondance — ~350-550€ AR",
    vol_prix: "350-550€ AR pour 2",
    compagnie: "Norwegian / SAS",
    iata: "BGO",
    logement: "Appartement Bryggen — 120-180€/nuit",
    type: ["nature", "fjords", "randonnee"],
    description: "Bergen + fjords norvégiens : Bryggen (UNESCO), Floibanen, Sognefjord, Flåm.",
    pois: [
      { nom: "Bryggen (UNESCO)", type: "culture", coords: [60.3975, 5.3232], prix: "Gratuit", lien: "" },
      { nom: "Floibanen (funiculaire)", type: "nature", coords: [60.3938, 5.3288], prix: "~11€ AR", lien: "" },
      { nom: "Sognefjord", type: "nature", coords: [61.1000, 6.6000], prix: "Excursion ~70-100€/pers", lien: "" },
      { nom: "Flåm (train de montagne)", type: "nature", coords: [60.8636, 7.1167], prix: "~35€/pers", lien: "" },
    ],
    gastronomie: ["Poissons & fruits de mer frais", "Raspeballer (boulettes pomme de terre)", "Fiskepudding", "Cloudberry jam"],
    valise_type: "randonnee",
    meteo: { temp: "15-21°C", nuit: "10-14°C" },
  },
  {
    id: "dubrovnik",
    nom: "Dubrovnik",
    pays: "Croatie",
    emoji: "🌊",
    statut: "projet",
    budget_min: 950, budget_max: 1500,
    coords: [42.6507, 18.0944],
    vol: "Correspondance — ~250-400€ AR",
    vol_prix: "250-400€ AR pour 2",
    compagnie: "Ryanair / Croatia Airlines",
    iata: "DBV",
    logement: "Appartement Lapad ou vieille ville — 80-130€/nuit",
    type: ["plage", "culture", "histoire"],
    description: "Dubrovnik : remparts (UNESCO), vieille ville Game of Thrones, îles environnantes, Boka Kotorska.",
    pois: [
      { nom: "Remparts de Dubrovnik", type: "culture", coords: [42.6411, 18.1083], prix: "~35€/pers", lien: "" },
      { nom: "Île de Lokrum", type: "nature", coords: [42.6233, 18.1253], prix: "~15€ ferry AR + entrée", lien: "" },
      { nom: "Plage de Banje", type: "plage", coords: [42.6461, 18.1136], prix: "Gratuit", lien: "" },
    ],
    gastronomie: ["Peka (viande sous cloche)", "Prstaci (palourdes), Buzara", "Maraschino (liqueur cerise)", "Plavac Mali (vin)"],
    valise_type: "plage",
    meteo: { temp: "28-33°C", mer: "25-26°C", nuit: "22-24°C" },
  },
  {
    id: "split",
    nom: "Split & Côte Dalmate",
    pays: "Croatie",
    emoji: "⛵",
    statut: "projet",
    budget_min: 850, budget_max: 1350,
    coords: [43.5081, 16.4402],
    vol: "Direct ou correspondance — ~200-350€ AR",
    vol_prix: "200-350€ AR pour 2",
    compagnie: "Ryanair / easyJet",
    iata: "SPU",
    logement: "Appartement centre (Diocletianovo) — 70-110€/nuit",
    type: ["plage", "culture", "ile"],
    description: "Split : Palais de Dioclétien (UNESCO), îles Brač/Hvar, côte dalmate.",
    pois: [
      { nom: "Palais de Dioclétien", type: "culture", coords: [43.5083, 16.4402], prix: "Gratuit (intérieur)", lien: "" },
      { nom: "Île de Hvar", type: "ile", coords: [43.1728, 16.4414], prix: "~10€ ferry", lien: "" },
      { nom: "Île de Brač (plage Zlatni Rat)", type: "plage", coords: [43.3211, 16.6349], prix: "~7€ ferry", lien: "" },
    ],
    gastronomie: ["Peka (agneau)", "Soparnik (tarte chard)", "Paški sir (fromage)", "Plavac Mali", "Prošek (vin doux)"],
    valise_type: "plage",
    meteo: { temp: "28-33°C", mer: "24-26°C", nuit: "20-23°C" },
  },
  {
    id: "dublin",
    nom: "Dublin",
    pays: "Irlande",
    emoji: "🍺",
    statut: "projet",
    budget_min: 950, budget_max: 1500,
    coords: [53.3498, -6.2603],
    vol: "Direct depuis NTE — ~150-250€ AR",
    vol_prix: "150-250€ AR pour 2",
    compagnie: "Ryanair / Aer Lingus",
    iata: "DUB",
    logement: "Appartement Temple Bar / Portobello — 90-130€/nuit",
    type: ["ville", "culture", "pub"],
    description: "Dublin : Trinity College (Livre de Kells), Guinness Storehouse, Temple Bar, falaises de Moher (excursion).",
    pois: [
      { nom: "Trinity College & Livre de Kells", type: "culture", coords: [53.3438, -6.2546], prix: "~16€/pers", lien: "" },
      { nom: "Guinness Storehouse", type: "culture", coords: [53.3419, -6.2868], prix: "~20€/pers", lien: "" },
      { nom: "Temple Bar", type: "detente", coords: [53.3455, -6.2646], prix: "Gratuit", lien: "" },
      { nom: "Falaises de Moher (excursion)", type: "nature", coords: [52.9720, -9.4264], prix: "~35-50€ excursion", lien: "" },
    ],
    gastronomie: ["Irish stew", "Full Irish breakfast", "Soda bread", "Fish & chips", "Guinness draught"],
    valise_type: "ville",
    meteo: { temp: "16-20°C", nuit: "12-15°C" },
  },
  {
    id: "edimbourg",
    nom: "Édimbourg",
    pays: "Écosse",
    emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    statut: "projet",
    budget_min: 900, budget_max: 1450,
    coords: [55.9533, -3.1883],
    vol: "Direct depuis NTE — ~150-280€ AR",
    vol_prix: "150-280€ AR pour 2",
    compagnie: "Ryanair / easyJet",
    iata: "EDI",
    logement: "Appartement New Town / Leith — 85-130€/nuit",
    type: ["ville", "culture", "histoire"],
    description: "Édimbourg : château, Royal Mile, Arthur's Seat, Fringe Festival, Highlands (excursion).",
    pois: [
      { nom: "Château d'Édimbourg", type: "culture", coords: [55.9486, -3.1999], prix: "~18€/pers", lien: "" },
      { nom: "Royal Mile", type: "culture", coords: [55.9503, -3.1883], prix: "Gratuit", lien: "" },
      { nom: "Arthur's Seat", type: "nature", coords: [55.9444, -3.1618], prix: "Gratuit", lien: "" },
      { nom: "Loch Ness (excursion)", type: "excursion", coords: [57.3229, -4.4244], prix: "~45-60€ excursion", lien: "" },
    ],
    gastronomie: ["Haggis", "Cullen skink (soupe fumée)", "Scotch pie", "Cranachan (dessert)", "Whisky single malt"],
    valise_type: "ville",
    meteo: { temp: "16-20°C", nuit: "10-14°C" },
  },

  // ── LONGS COURRIERS ───────────────────────────────────────
  {
    id: "guadeloupe",
    nom: "Guadeloupe",
    pays: "France (DOM)",
    emoji: "🌴",
    statut: "projet_longterme",
    budget_min: 2200, budget_max: 3500,
    coords: [16.2650, -61.5510],
    vol: "Vol direct depuis CDG — ~600-900€ AR",
    vol_prix: "600-900€ AR pour 2",
    compagnie: "Air France / Corsair",
    iata: "PTP",
    logement: "Gîte ou villa — 80-150€/nuit",
    type: ["plage", "nature", "randonnee"],
    description: "Guadeloupe : Grande-Terre, Basse-Terre, La Soufrière, Marie-Galante, îles des Saintes.",
    pois: [
      { nom: "Volcan La Soufrière", type: "randonnee", coords: [16.0444, -61.6639], prix: "~5€ parking", lien: "" },
      { nom: "Îles des Saintes", type: "plage", coords: [15.8667, -61.6167], prix: "~30€ ferry AR", lien: "" },
      { nom: "Chutes du Carbet", type: "nature", coords: [16.0281, -61.6069], prix: "Gratuit", lien: "" },
      { nom: "Plage de la Caravelle", type: "plage", coords: [16.3239, -61.4756], prix: "Gratuit", lien: "" },
    ],
    gastronomie: ["Accras de morue", "Colombo poulet", "Boudin antillais", "Chatrou (pieuvre)", "Ti-punch"],
    valise_type: "plage_randonnee",
    meteo: { temp: "28-31°C", mer: "27°C", nuit: "24-26°C" },
  },
  {
    id: "reunion",
    nom: "La Réunion",
    pays: "France (DOM)",
    emoji: "🌋",
    statut: "projet_longterme",
    budget_min: 2500, budget_max: 4000,
    coords: [-21.1151, 55.5364],
    vol: "Vol depuis CDG (escale possible Maurice) — ~700-1200€ AR",
    vol_prix: "700-1200€ AR pour 2",
    compagnie: "Air France / Air Austral",
    iata: "RUN",
    logement: "Gîte — 60-100€/nuit",
    type: ["nature", "randonnee", "volcan"],
    description: "La Réunion : Piton de la Fournaise, Cirques de Cilaos/Mafate/Salazie, Grand Raid.",
    pois: [
      { nom: "Piton de la Fournaise", type: "randonnee", coords: [-21.2444, 55.7083], prix: "Gratuit (accès)", lien: "" },
      { nom: "Cirque de Cilaos", type: "nature", coords: [-21.1367, 55.4722], prix: "Gratuit", lien: "" },
      { nom: "Cirque de Mafate", type: "randonnee", coords: [-21.0750, 55.4333], prix: "Gratuit", lien: "" },
      { nom: "Trou de Fer (cascade)", type: "nature", coords: [-21.0706, 55.6403], prix: "Gratuit", lien: "" },
    ],
    gastronomie: ["Carry poulet malgache", "Rougail saucisses", "Cari requin", "Bonbon piment", "Rhum arrangé"],
    valise_type: "randonnee",
    meteo: { temp: "24-30°C", nuit: "18-22°C" },
  },
  {
    id: "tahiti",
    nom: "Tahiti / Polynésie française",
    pays: "France (COM)",
    emoji: "🌺",
    statut: "projet_longterme",
    budget_min: 4000, budget_max: 7000,
    coords: [-17.5334, -149.5667],
    vol: "Vol depuis CDG (12h+) — ~1500-2500€ AR",
    vol_prix: "1500-2500€ AR pour 2",
    compagnie: "Air France / Air Tahiti Nui",
    iata: "PPT",
    logement: "Pension de famille / bungalow — 80-200€/nuit",
    type: ["plage", "nature", "detente"],
    description: "Tahiti, Moorea, Bora Bora. Snorkeling, lagons, jardins de coraux, raies et requins inoffensifs.",
    pois: [
      { nom: "Bora Bora — lagon", type: "plage", coords: [-16.5004, -151.7415], prix: "Ferry + activités", lien: "" },
      { nom: "Moorea — Mont Rotui", type: "nature", coords: [-17.5500, -149.8167], prix: "Gratuit", lien: "" },
    ],
    gastronomie: ["Poisson cru (ia ota)", "Ma'a tinito (porc carottes)", "Po'e (dessert fruit)", "Jus de fruits frais"],
    valise_type: "plage",
    meteo: { temp: "27-30°C", mer: "27°C", nuit: "23-25°C" },
  },
  {
    id: "bahamas",
    nom: "Bahamas",
    pays: "Bahamas",
    emoji: "🐚",
    statut: "projet_longterme",
    budget_min: 4500, budget_max: 8000,
    coords: [25.0480, -77.3554],
    vol: "CDG + correspondance Miami — ~1800-3000€ AR",
    vol_prix: "1800-3000€ AR pour 2",
    compagnie: "American Airlines / Bahamasair",
    iata: "NAS",
    logement: "Resort ou appartement — 120-250€/nuit",
    type: ["plage", "mer", "detente"],
    description: "Nassau, Paradise Island, plages de sable rose, snorkeling, plongée dans les blue holes.",
    pois: [
      { nom: "Cable Beach", type: "plage", coords: [25.0758, -77.3630], prix: "Gratuit", lien: "" },
      { nom: "Atlantis Resort (aquarium)", type: "culture", coords: [25.0878, -77.3247], prix: "~40€/pers jour", lien: "" },
      { nom: "Blue Lagoon Island", type: "excursion", coords: [25.0800, -77.2900], prix: "~50€ excursion", lien: "" },
    ],
    gastronomie: ["Conch fritters (lambi)", "Rock Lobster grillé", "Guava duff (dessert)", "Rum punch", "Sky Juice (gin coco)"],
    valise_type: "plage",
    meteo: { temp: "29-32°C", mer: "27°C", nuit: "24-26°C" },
  },
];

// ── TEMPLATES VALISES ──────────────────────────────────────

const VALISE_TEMPLATES = {
  plage: {
    label: "Plage & Mer",
    categories: {
      "Vêtements Elle": [
        "Robes légères x6", "Tenue de soirée x1", "Veste légère x1",
        "Maillots de bain x3", "Paréo / sarong", "Tunique / kaftan",
        "Sous-vêtements x6", "Chaussettes x3 paires",
        "Sandales soirée", "Tongs / claquettes plage", "Chapeau large bord"
      ],
      "Vêtements Lui": [
        "Shorts + t-shirts x6", "Tenue de soirée x1 (chemise)", "Veste légère x1",
        "Maillots de bain x3", "Sous-vêtements x6", "Chaussettes x3 paires",
        "Sandales soirée", "Tongs / claquettes plage", "Casquette / chapeau"
      ],
      "Plage & Mer": [
        "Serviettes microfibre x2 (l'hôtel ne prête pas !)",
        "Masque + tuba x2", "Chaussons néoprène x2",
        "Sac étanche dry bag 10-20L", "Sacs zip étanches x4",
        "Crème solaire SPF 50+ x3 tubes", "Spray solaire cheveux UV",
        "Après-soleil x2", "Lunettes de soleil UV400 x2"
      ],
      "Santé": [
        "Anti-nausées (Nautamine/Vogalib)", "Antidouleur (ibuprofène + paracétamol)",
        "Anti-diarrhée (Imodium)", "Antihistaminique", "Antiseptique + pansements",
        "Répulsif moustiques x2", "SRO x2-3 sachets", "CEAM x2"
      ],
      "Tech & Pratique": [
        "Carte CNI valide x2", "Passeport x2 (si requis)",
        "Powerbank 10 000 mAh", "Câbles recharge (USB-C)",
        "Appareil photo / GoPro", "Support téléphone voiture",
        "Masque de nuit + bouchons (avion)", "Liseuse ou livre"
      ],
      "Hygiène (en soute)": [
        "Shampoing + après-shampoing", "Gel douche x2", "Déodorant x2",
        "Rasoir + mousse", "Dentifrice + brosses", "Crème hydratante",
        "Maquillage", "Parfum (soute obligatoire)", "Préservatifs"
      ]
    }
  },
  ville: {
    label: "Ville & Culture",
    categories: {
      "Vêtements Elle": [
        "Tenues légères jour x5", "Tenue soirée x1", "Veste légère x1",
        "Chaussures confortables marche", "Sandales soirée",
        "Sous-vêtements x5", "Chaussettes x4 paires"
      ],
      "Vêtements Lui": [
        "Shorts/pantalons + t-shirts x5", "Chemise soirée x1", "Veste légère x1",
        "Baskets / chaussures marche confortables", "Chaussures soirée",
        "Sous-vêtements x5", "Chaussettes x4 paires"
      ],
      "Santé": [
        "Antidouleur (ibuprofène + paracétamol)", "Anti-diarrhée (Imodium)",
        "Antihistaminique", "Antiseptique + pansements", "Crème solaire SPF 30+",
        "Lunettes de soleil", "CEAM x2 (si Europe)"
      ],
      "Tech & Pratique": [
        "Carte CNI valide x2", "Powerbank 10 000 mAh",
        "Câbles recharge", "Écouteurs x2",
        "Appareil photo", "Masque de nuit + bouchons (avion)"
      ],
      "Hygiène (en soute)": [
        "Shampoing + après-shampoing", "Gel douche x2", "Déodorant x2",
        "Dentifrice + brosses", "Crème hydratante", "Maquillage", "Parfum"
      ]
    }
  },
  plage_randonnee: {
    label: "Plage + Randonnée",
    categories: {
      "Vêtements Elle": [
        "Robes légères x6", "Tenue de soirée x1", "Tenue rando (pantalon léger) x1",
        "Veste légère x1", "Maillots de bain x3", "Paréo / sarong",
        "Sous-vêtements x6", "Chaussettes x3 paires + chaussettes rando x2",
        "Chaussures de randonnée FERMÉES (obligatoire)", "Sandales soirée", "Tongs plage", "Chapeau large"
      ],
      "Vêtements Lui": [
        "Shorts + t-shirts x5", "Pantalon léger rando x1", "Veste légère x1",
        "Maillots de bain x3", "Sous-vêtements x6",
        "Chaussettes x3 + chaussettes rando x2",
        "Chaussures de randonnée FERMÉES (obligatoire)", "Sandales soirée", "Tongs plage", "Casquette"
      ],
      "Randonnée": [
        "Sac à dos randonnée x2", "Gourdes 1L x2",
        "Pansements anti-ampoules Compeed x2 boites",
        "Bâtons de marche pliables (optionnel)", "Snacks trail (barres, fruits secs)",
        "SRO x3 sachets (coup de chaleur)"
      ],
      "Plage & Mer": [
        "Serviettes microfibre x2", "Masque + tuba x2", "Chaussons néoprène x2",
        "Sac étanche dry bag", "Crème solaire SPF 50+ x3", "Après-soleil x2",
        "Lunettes de soleil x2"
      ],
      "Santé": [
        "Antidouleur (ibuprofène + paracétamol)", "Anti-nausées",
        "Anti-diarrhée", "Antihistaminique", "Antiseptique + pansements",
        "Répulsif moustiques x2", "CEAM x2"
      ],
      "Tech & Pratique": [
        "Carte CNI / Passeport x2", "Powerbank 10 000 mAh",
        "GoPro + flotteur GoPro (CRITIQUE en mer)", "Câbles recharge",
        "Support téléphone voiture", "Appareil photo", "Google Maps hors-ligne"
      ],
      "Hygiène": [
        "Shampoing + après-shampoing", "Gel douche x2", "Déodorant x2",
        "Dentifrice + brosses", "Crème hydratante", "Maquillage", "Parfum"
      ]
    }
  },
  randonnee: {
    label: "Nature & Randonnée",
    categories: {
      "Vêtements Elle": [
        "Pantalons légers rando x2", "T-shirts techniques x4", "Sous-couche légère x1",
        "Veste imperméable", "Maillots de bain x2 (baignade en rivière)",
        "Sous-vêtements x5", "Chaussettes rando x4 paires",
        "Chaussures de randonnée HAUTES (obligatoire)", "Sandales légères le soir"
      ],
      "Vêtements Lui": [
        "Pantalons légers rando x2", "T-shirts techniques x4", "Sous-couche légère x1",
        "Veste imperméable", "Maillots de bain x2",
        "Sous-vêtements x5", "Chaussettes rando x4 paires",
        "Chaussures de randonnée HAUTES (obligatoire)", "Sandales légères"
      ],
      "Randonnée": [
        "Sac à dos 30-40L x2", "Gourdes 1L x2 (ou poche à eau)",
        "Bâtons de marche pliables x2 paires",
        "Pansements anti-ampoules Compeed x2 boites",
        "Couverture de survie x2", "Lampe frontale x2 + piles",
        "Snacks trail (barres, fruits secs, noix)",
        "SRO x5 sachets"
      ],
      "Santé": [
        "Antidouleur (ibuprofène + paracétamol)", "Anti-diarrhée",
        "Antihistaminique", "Antiseptique + kit pansements complet",
        "Répulsif moustiques x2 (spray fort)", "Crème solaire SPF 50+",
        "Crème anti-frottement"
      ],
      "Tech": [
        "Powerbank solaire ou grande capacité", "GoPro + accessoires",
        "Câbles + chargeur", "Appareil photo", "Carte IGN / carte hors-ligne"
      ]
    }
  }
};

// Airports IATA → code Skyscanner
const IATA_CODES = {
  "NTE": "ntes", "CDG": "cdg", "HER": "her", "OPO": "opo", "PSA": "psa",
  "MAD": "mad", "AMS": "ams", "MAH": "mah", "ATH": "ath", "BER": "ber",
  "MUC": "mun", "PRG": "prg", "TIA": "tia", "ARN": "sto", "OSL": "osl",
  "BGO": "bgo", "DBV": "dbv", "SPU": "spu", "DUB": "dub", "EDI": "edi",
  "PTP": "ptp", "RUN": "reu", "PPT": "ppt", "NAS": "nas",
};

const STATUT_CONFIG = {
  confirme:          { label: "✅ Confirmé",        cls: "confirme",          color: "#22c55e" },
  planification:     { label: "🔍 En planification", cls: "planification",     color: "#f59e0b" },
  projet:            { label: "📋 Projet Europe",    cls: "projet",            color: "#6366f1" },
  projet_longterme:  { label: "🌍 Long courrier",    cls: "projet-longterme",  color: "#8b5cf6" },
};

const TYPE_ICONS = {
  plage: "🏖️", mer: "🌊", ville: "🏙️", culture: "🏛️",
  nature: "🌿", randonnee: "🥾", art: "🎨", gastronomie: "🍽️",
  histoire: "📜", ile: "🏝️", fjords: "🏔️", velo: "🚲",
  pub: "🍺", biere: "🍺", streetart: "🎨", volcan: "🌋", detente: "😎"
};

// ── PRÉRÉGLAGES AGENDA (générés depuis le vault Obsidian) ──
// h/m = heure de début, dur = durée en minutes. d = index du jour (0 = 1er jour).
const AGENDA_PRESETS = {
  heraklion: {
    hstart: 6, hend: 24,
    blocks: [
      // J1 — Lun 6 juillet : Départ + Arrivée + Installation
      { d:0, h:7,  m:50, dur:270, type:"transport", emoji:"✈️", label:"Vol CDG → Héraklion (TUI)" },
      { d:0, h:13, m:30, dur:60,  type:"perso",     emoji:"🏨", label:"Arrivée hôtel + check-in" },
      { d:0, h:14, m:30, dur:60,  type:"repas",     emoji:"🍽️", label:"Déjeuner all-inclusive" },
      { d:0, h:16, m:0,  dur:150, type:"plage",     emoji:"🏖️", label:"Piscine + repérage hôtel", chill:true },
      { d:0, h:18, m:30, dur:60,  type:"detente",   emoji:"🚶", label:"Balade plage (500 m)", chill:true },
      { d:0, h:20, m:0,  dur:90,  type:"repas",     emoji:"🍷", label:"Premier dîner AI + coucher de soleil" },
      // J2 — Mar 7 juillet : Knossos + Malia + Héraklion
      { d:1, h:8,  m:0,  dur:45,  type:"repas",     emoji:"🥐", label:"Petit-déjeuner buffet" },
      { d:1, h:8,  m:45, dur:15,  type:"transport", emoji:"🔑", label:"Location voiture (face hôtel)" },
      { d:1, h:9,  m:0,  dur:90,  type:"culture",   emoji:"🏛️", label:"Ruines de Malia (~6€/pers)" },
      { d:1, h:10, m:30, dur:30,  type:"transport", emoji:"🚗", label:"Route Malia → Knossos" },
      { d:1, h:11, m:0,  dur:135, type:"culture",   emoji:"🏛️", label:"Palais de Knossos (~16€/pers)" },
      { d:1, h:13, m:30, dur:60,  type:"repas",     emoji:"🛒", label:"Marché 1866 + déjeuner de rue" },
      { d:1, h:14, m:30, dur:120, type:"culture",   emoji:"🏙️", label:"Vieille ville d'Héraklion" },
      { d:1, h:16, m:30, dur:60,  type:"transport", emoji:"🚗", label:"Retour hôtel + restitution voiture" },
      { d:1, h:17, m:30, dur:150, type:"plage",     emoji:"🏖️", label:"Piscine, douche, repos", chill:true },
      { d:1, h:20, m:0,  dur:60,  type:"repas",     emoji:"🍷", label:"Dîner all-inclusive" },
      { d:1, h:21, m:0,  dur:90,  type:"detente",   emoji:"🍹", label:"Soirée Hersonissos (option)", chill:true },
      // J3 — Mer 8 juillet : Détente + 🎁 Croisière île de Dia
      { d:2, h:8,  m:30, dur:60,  type:"repas",     emoji:"🥐", label:"Petit-déjeuner" },
      { d:2, h:9,  m:30, dur:180, type:"plage",     emoji:"🏖️", label:"Matinée libre piscine / plage", chill:true },
      { d:2, h:12, m:30, dur:45,  type:"repas",     emoji:"🍽️", label:"Déjeuner all-inclusive" },
      { d:2, h:13, m:15, dur:75,  type:"transport", emoji:"🚗", label:"Route → port d'Héraklion" },
      { d:2, h:15, m:0,  dur:360, type:"excursion", emoji:"⛵", label:"🎁 Croisière île de Dia (surprise)" },
      { d:2, h:21, m:35, dur:35,  type:"transport", emoji:"🚗", label:"Retour hôtel (~22h10)" },
      // J4 — Jeu 9 juillet : Gorges de Samaria
      { d:3, h:6,  m:30, dur:30,  type:"perso",     emoji:"⏰", label:"Réveil + préparation sac" },
      { d:3, h:7,  m:0,  dur:90,  type:"transport", emoji:"🚌", label:"Bus excursion → Xyloskalo" },
      { d:3, h:9,  m:0,  dur:270, type:"nature",    emoji:"🥾", label:"Gorges de Samaria (16 km de descente)" },
      { d:3, h:13, m:30, dur:105, type:"repas",     emoji:"🍽️", label:"Déjeuner + baignade Agia Roumeli" },
      { d:3, h:15, m:15, dur:60,  type:"transport", emoji:"⛴️", label:"Ferry → Hora Sfakion (12,50€)" },
      { d:3, h:16, m:30, dur:120, type:"transport", emoji:"🚌", label:"Bus retour Anissaras" },
      { d:3, h:18, m:30, dur:90,  type:"repas",     emoji:"🍷", label:"Dîner all-inclusive" },
      // J5 — Ven 10 juillet : Est Crète + 🎁 Dîner Koutouloufari
      { d:4, h:9,  m:0,  dur:30,  type:"repas",     emoji:"🥐", label:"Petit-déjeuner" },
      { d:4, h:9,  m:30, dur:20,  type:"transport", emoji:"🔑", label:"Location voiture" },
      { d:4, h:9,  m:50, dur:40,  type:"transport", emoji:"🚗", label:"Route → Elounda" },
      { d:4, h:10, m:30, dur:120, type:"culture",   emoji:"⛴️", label:"Bateau + île de Spinalonga" },
      { d:4, h:13, m:0,  dur:120, type:"repas",     emoji:"🍽️", label:"Déjeuner Elounda (vue Mirabello)" },
      { d:4, h:15, m:0,  dur:90,  type:"ville",     emoji:"🏙️", label:"Agios Nikolaos + lac Voulismeni" },
      { d:4, h:17, m:0,  dur:165, type:"plage",     emoji:"🏖️", label:"Piscine, douche, repos", chill:true },
      { d:4, h:20, m:0,  dur:150, type:"repas",     emoji:"🌙", label:"🎁 Dîner romantique Koutouloufari" },
      // J6 — Sam 11 juillet : Matin libre + Retour CDG
      { d:5, h:8,  m:0,  dur:60,  type:"repas",     emoji:"🥐", label:"Dernier petit-déjeuner AI" },
      { d:5, h:9,  m:0,  dur:90,  type:"plage",     emoji:"🏖️", label:"Matin libre (plage / souvenirs)", chill:true },
      { d:5, h:10, m:30, dur:30,  type:"perso",     emoji:"🧳", label:"Check-out hôtel" },
      { d:5, h:11, m:0,  dur:30,  type:"transport", emoji:"🚗", label:"Transfer TUI → aéroport HER" },
      { d:5, h:13, m:20, dur:210, type:"transport", emoji:"✈️", label:"Vol HER → Paris CDG" },
    ],
  },
};

// ── Exposition pour les modules ES (store/model/vues) ──
// data.js reste un script classique ; on publie les données sur window
// pour que les modules (chargés en defer) puissent les lire.
Object.assign(window, { DESTINATIONS, VALISE_TEMPLATES, AGENDA_PRESETS, IATA_CODES, STATUT_CONFIG, TYPE_ICONS });
